### ISSUE TITLE
Concatenation option?

### ISSUE THREAD

**Issue by objectkit** [abagshaw/brackets-minifier#11]
I may have missed something, but if not, I'd like to request:
- being able to concatenate all files together into one file e.g. _build.js_
- having two build files output 
  -  _build.min.js_  (minified concatenated file) 
  -  _build.js_ (concatenated file, no minification)
- specify an output name for build files (default name could be "build"?)

Hope that makes sense... what do you think?

**Comment by abagshaw** [comment]
Thanks @objectkit - this is a great suggestion and definitely something I hope to integrate into this plugin. Unfortunately I don't have time to work on that right now but in a few months when I have more free time I'll should be able to get concatenation integrated.

**Comment by snakeman21** [comment]
Sorry, don't mean to be annoying, but I was wondering if this is still being considered as a feature to add. This would really set this plugin apart from others, as it would really simplify concatenating + minifying files. The minifying part is awesome already for my css/js files, so thank you for such a great plugin.

**Comment by abagshaw** [comment]
Yeah sorry about that - I totally see how this could be a big improvement for the plugin and I'd love to add this functionality but I'm swamped with school at the moment. When I have some time on my hands I'll do my best to get around to this.

**Comment by snakeman21** [comment]
Completely understandable, this is still the best minifier for Brackets anyway. Thanks for making a great plugin.

**Comment by onclave** [comment]
I was actually looking desperately for this feature to minify all files into one file. This option would be great. Looking forward to it. Thanks.

**Comment by abagshaw** [comment]
Good news - concatenation is finally here! Update has been pushed to brackets registry and the plugin can be updated. See information on how to use the new concatenation feature in the readme.
