### ISSUE TITLE
base64 images causes W3C CSS Validator errors

### ISSUE THREAD

**Issue by hongily25** [abagshaw/brackets-minifier#13]
The minifier strips quotation marks from background-image: url("data:image/png;base64....") which causes the W3C Validator to mark them as errors.

**Comment by abagshaw** [comment]
Yes it does appear to be removing the quotes in the minified version. Minification in this plugin is done through cleancss, see: https://github.com/jakubpawlowicz/clean-css

If there is a space in the url the quotes will be retained in the minified version, however if no space is present they won't as its not necessary to resolve the url or the data. Maybe its not 'technically' in line with CSS specs - but I don't think it causes any issues for any browser/client reading the minified CSS file - correct me if I'm wrong though.

You can report this bug to the cleancss repo as they are the ones that would need to fix this issue if you would like

**Comment by hongily25** [comment]
Ok thanks! They are already aware of this issue and will address in a future release. https://github.com/jakubpawlowicz/clean-css/issues/763
