### ISSUE TITLE
I get absolutely no response from this minifier

### ISSUE THREAD

**Issue by NJseo** [abagshaw/brackets-minifier#14]
I been playing around with it for the last 30 minutes. No response.

**Comment by abagshaw** [comment]
Could you elaborate a bit on your problem? 

When you press `Cmd/Ctrl+Alt+M` a new minified JS or CSS file should be placed in the same directory as the original file with the name `yourname.min.css` or `yourname.min.js` for example. 

You should also see a message at the bottom right of your brackets window that says "Minified" for a few seconds and disappears. If no minified file is created, look at the bottom right for any error messages and post them here - as well please check the Developer Tools Console for any additional error messages by going to Debug -> Show Developer Tools and clicking on the Console tab at the top.

**Comment by NJseo** [comment]
I guess I missed it because I had different expectations. It did optimize individual files and foldered them. What I was expecting is that they would collect into one file. It would be nice to have a plugin or script that could enable me to use bueatiful code, but compresses HTML,CSS, and JS live on the domain.

**Comment by abagshaw** [comment]
I believe such plugins do exist for Brackets (plugins that perform concatenation) - but I'm not sure if they also do minification. 

The concatenation feature has already been requested by someone else, see #11 and if I have some time I'll work on getting it implemented, but for the time being, this plugins remains a minification plugin solely.
