### ISSUE TITLE
Features of this minifier 

### ISSUE THREAD

**Issue by SheepDomination** [abagshaw/brackets-minifier#15]
This minifier needs to be able to do what [this](https://github.com/tssajo/Minify) minifier can do in Sublime.

**Comment by abagshaw** [comment]
What exactly are the features you would like to see added to brackets-minifier?

**Comment by SheepDomination** [comment]
HTML & SVG as well the ability to work offline.

**Comment by abagshaw** [comment]
HTML & SVG may be added in the future if there is enough demand for it (and if I or someone else has time to put it in). I'm not sure what you mean when you say "the ability to work offline". This plugin doesn't require an internet connection - all processing is done locally.

**Comment by lauriinc** [comment]
Is there a possibility now or possibly in the future that all console.log are removed in the output when the JS is minified?

**Comment by abagshaw** [comment]
@lauriinc You can certainly do that by using the `drop_console` [compress option](https://github.com/mishoo/UglifyJS2#compress-options) with UglifyJS. You would want to specify that in the [Minifier Options](https://github.com/abagshaw/brackets-minifier#minifier-options) area.

I'm going to close this issue as HTML & SVG is not likely to be added to this plugin. I'd like to keep this just to JS and CSS minification.
