### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by manuel-84** [abagshaw/brackets-minifier#16]
When I save a file it should compile the minified version, but there is an error:
Name expected  @ main.js : 143

**Comment by abagshaw** [comment]
I'll look into this a bit further but can you verify this is an issue with the plugin and not your code? It could very well be an error from UglifyJS saying there was a problem minifying your js because of something.

Can you create a new js file, write something simple and then try to minify that?

**Comment by manuel-84** [comment]
Yep, it was a mistake in the code (,; at the end of a statement), thanks
