### ISSUE TITLE
Preserve License Comments

### ISSUE THREAD

**Issue by tovic** [abagshaw/brackets-minifier#18]
How can I keep JavaScript/CSS comments prefixed by `/*!` or `/**` or contains `@license` in the block? Editing the options parameters in UglifyJS/CSS instance from the source did not change anything.

**Comment by abagshaw** [comment]
Sorry for the delay - this certainly seems possible in UglifyJS as I think they have a feature for that. I'm not sure about cleancss though. I'll see if I can get around to adding that option in the UI soon.

**Comment by tovic** [comment]
~~~ .javascript
{
  compress: { … },
  output: {
    …
    …
    comments: /@license|@preserve|^[!*]/
  }
}
~~~

**Comment by abagshaw** [comment]
It should now be possible with brackets-minifier v3.0.0 to preserve comments (licences or otherwise) by passing the appropriate options with https://github.com/abagshaw/brackets-minifier#minifier-options
