### ISSUE TITLE
Finnish Translation for 1.1.0

### ISSUE THREAD

**Issue by abagshaw** [abagshaw/brackets-minifier#2]
I would like to keep the Finnish translation going and the next version of this plugin has a lot more features which require more strings translation. If someone (specifically @valtlait ) could translate the attached file as soon as possible that would be great!

English Strings File:
http://1drv.ms/1LLmzRj

P.S. Not that I need to say this...but please keep any HTML intact.

**Comment by valtlait** [comment]
@abagshaw PR #5 sent

**Comment by abagshaw** [comment]
Thanks very much!
