### ISSUE TITLE
Concatenate on Save Option

### ISSUE THREAD

**Issue by snakeman21** [abagshaw/brackets-minifier#20]
Love the concatenation option and I've been enjoying using it on several different projects. However, I think it would be a useful feature to allow concatenation on save, rather than just on project minification.

**Comment by abagshaw** [comment]
@snakeman21 Right now the concatenation feature is tied into the project minification pipeline as concatenation inherently requires more than one file to be of any use - now there is a setting at the very top of the `Minifier Project Preferences` called `Minify Project on Save` and turning this on should allow your concatenated files to be re-generated any time a file within your project is saved. Are you looking for some different functionality though?

**Comment by snakeman21** [comment]
Wow, I feel stupid now. Forgot that you can just do minify _project_ on save. So sorry to raise a false issue. Thanks again for this awesome plugin!
