### ISSUE TITLE
Minifier create new min file

### ISSUE THREAD

**Issue by kashifkiduniya** [abagshaw/brackets-minifier#28]
When i minify css it creates new style.min.css file.
How can i minfy my current file?

**Comment by abagshaw** [comment]
@kashifkiduniya I'm not sure if I understand your question. To minify the current file you can follow the steps outlined for [Single File Minification](https://github.com/abagshaw/brackets-minifier#single-file-minification).

**Comment by kashifkiduniya** [comment]
Can i just minfiy my current code?
Right now issue is that when i minfy my file it creates new min file.
Please see [screenshot](http://prntscr.com/hqp73e)

**Comment by abagshaw** [comment]
@kashifkiduniya brackets-minifier is not designed to minify code in-place, instead it creates a new minified file based off the unminified file. That way you can continue to edit the non-minified file and have changes updated in the minified file.
