### ISSUE TITLE
Italian Translation for 1.1.0

### ISSUE THREAD

**Issue by abagshaw** [abagshaw/brackets-minifier#3]
I would like to keep the Italian translation going and the next version of this plugin has a lot more features which require more strings translation. If someone (specifically @Denisov21 ) could translate the attached file as soon as possible that would be great!

English Strings File:
http://1drv.ms/1LLmzRj

P.S. Not that I need to say this...but please keep any HTML intact

**Comment by Denisov21** [comment]
Done @abagshaw!

Good bye!

**Comment by abagshaw** [comment]
Awesome, thanks!
