### ISSUE TITLE
Minification on save just minimizes Brackets in OSX

### ISSUE THREAD

**Issue by BMOv2600** [abagshaw/brackets-minifier#7]
The brackets-minifier README.md states

>To minify a file, use the keyboard shortcut Cmd/Ctrl+M

According to [Adobe's User Key Bindings](https://github.com/adobe/brackets/wiki/User-Key-Bindings) **Cmd-M** "cannot be overridden on Mac."

Adding this override to keymap.json didn't seem to help either, even with the corresponding change in the main.js file.
```
"overrides": {
        "Cmd-Alt-M": "minifier.min"
    }
```

Are there any other ways to minimize a file w/this extension?

**Comment by abagshaw** [comment]
That certainly is a problem. I think we're going to have to switch the command to something different. I haven't bothered to change any of the commands when I ported this over from https://github.com/wylst/brackets-minifier

But maybe it needs to be changed. I think it wouldn't make sense to have different commands on Mac and on PC.

How about `Ctrl/Cmd + Shift + M` for File minification and `Ctrl/Cmd + Alt + M` for Project Minification?

**Comment by abagshaw** [comment]
Issue should be fixed in eb0e862734c008be61e9f9085972a272853eea0a

The extension will be updated on the brackets registry shortly. Please report back if this fixes your problem.
