### ISSUE TITLE
fix console errors

### ISSUE THREAD

**Issue by markhillard** [abagshaw/brackets-minifier#8]
Not a serious issue, but noticed the following errors in console after opening brackets:

> Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.

Looks like an easy fix...

[main.js#L267](https://github.com/abagshaw/brackets-minifier/blob/master/main.js#L267)

```js
DocumentManager.on("documentSaved", function(event, doc) {
    ...
});
```

[main.js#L301](https://github.com/abagshaw/brackets-minifier/blob/master/main.js#L301)

```js
automaton.on('checkedStateChange', function() {
    ...
});
```

**Comment by abagshaw** [comment]
This should be fixed in the updated version.
